package server

import "net/http"

var StatusMsg = map[int]string{
	http.StatusContinue:           "",
	http.StatusSwitchingProtocols: "",
	http.StatusProcessing:         "",
	http.StatusEarlyHints:         "",

	http.StatusOK:                   "成功",
	http.StatusCreated:              "成功创建",
	http.StatusAccepted:             "成功接收",
	http.StatusNonAuthoritativeInfo: "",
	http.StatusNoContent:            "",
	http.StatusResetContent:         "",
	http.StatusPartialContent:       "",
	http.StatusMultiStatus:          "",
	http.StatusAlreadyReported:      "",
	http.StatusIMUsed:               "",

	http.StatusMultipleChoices:   "",
	http.StatusMovedPermanently:  "",
	http.StatusFound:             "",
	http.StatusSeeOther:          "",
	http.StatusNotModified:       "",
	http.StatusUseProxy:          "",
	http.StatusTemporaryRedirect: "",
	http.StatusPermanentRedirect: "",

	http.StatusBadRequest:                   "请求参数错误",
	http.StatusUnauthorized:                 "",
	http.StatusPaymentRequired:              "",
	http.StatusForbidden:                    "",
	http.StatusNotFound:                     "",
	http.StatusMethodNotAllowed:             "",
	http.StatusNotAcceptable:                "",
	http.StatusProxyAuthRequired:            "",
	http.StatusRequestTimeout:               "",
	http.StatusConflict:                     "",
	http.StatusGone:                         "",
	http.StatusLengthRequired:               "",
	http.StatusPreconditionFailed:           "",
	http.StatusRequestEntityTooLarge:        "",
	http.StatusRequestURITooLong:            "",
	http.StatusUnsupportedMediaType:         "",
	http.StatusRequestedRangeNotSatisfiable: "",
	http.StatusExpectationFailed:            "",
	http.StatusTeapot:                       "",
	http.StatusMisdirectedRequest:           "",
	http.StatusUnprocessableEntity:          "",
	http.StatusLocked:                       "",
	http.StatusFailedDependency:             "",
	http.StatusTooEarly:                     "",
	http.StatusUpgradeRequired:              "",
	http.StatusPreconditionRequired:         "",
	http.StatusTooManyRequests:              "",
	http.StatusRequestHeaderFieldsTooLarge:  "",
	http.StatusUnavailableForLegalReasons:   "",

	http.StatusInternalServerError:           "系统错误，请联系开发人员",
	http.StatusNotImplemented:                "",
	http.StatusBadGateway:                    "",
	http.StatusServiceUnavailable:            "",
	http.StatusGatewayTimeout:                "",
	http.StatusHTTPVersionNotSupported:       "",
	http.StatusVariantAlsoNegotiates:         "",
	http.StatusInsufficientStorage:           "",
	http.StatusLoopDetected:                  "",
	http.StatusNotExtended:                   "",
	http.StatusNetworkAuthenticationRequired: "",
}
